CREATE SEQUENCE IF NOT EXISTS custom_rev_info_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS verification_token_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE attendance
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    attendance_status      VARCHAR(255)                            NOT NULL,
    session_participant_id BIGINT,
    CONSTRAINT pk_attendance PRIMARY KEY (id)
);

CREATE TABLE attendance_aud
(
    rev                    INTEGER NOT NULL,
    revtype                SMALLINT,
    id                     BIGINT  NOT NULL,
    start_time             TIMESTAMP WITHOUT TIME ZONE,
    end_time               TIMESTAMP WITHOUT TIME ZONE,
    attendance_status      VARCHAR(255),
    session_participant_id BIGINT,
    CONSTRAINT pk_attendance_aud PRIMARY KEY (rev, id)
);

CREATE TABLE custom_rev_info
(
    id         INTEGER NOT NULL,
    timestamp  BIGINT  NOT NULL,
    username   VARCHAR(255),
    ip_address VARCHAR(255),
    CONSTRAINT pk_custom_rev_info PRIMARY KEY (id)
);

CREATE TABLE dashboard
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_dashboard PRIMARY KEY (id)
);

CREATE TABLE dashboard_aud
(
    rev     INTEGER NOT NULL,
    revtype SMALLINT,
    id      BIGINT  NOT NULL,
    CONSTRAINT pk_dashboard_aud PRIMARY KEY (rev, id)
);

CREATE TABLE export_history
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    export_status VARCHAR(255)                            NOT NULL,
    export_format VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_export_history PRIMARY KEY (id)
);

CREATE TABLE export_history_aud
(
    rev           INTEGER NOT NULL,
    revtype       SMALLINT,
    id            BIGINT  NOT NULL,
    export_status VARCHAR(255),
    export_format VARCHAR(255),
    CONSTRAINT pk_export_history_aud PRIMARY KEY (rev, id)
);

CREATE TABLE notifications
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    notification_type   VARCHAR(255)                            NOT NULL,
    notification_status VARCHAR(255)                            NOT NULL,
    to_email            VARCHAR(255)                            NOT NULL,
    subject             VARCHAR(255)                            NOT NULL,
    failure_reason      VARCHAR(255),
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TABLE notifications_aud
(
    rev                 INTEGER NOT NULL,
    revtype             SMALLINT,
    id                  BIGINT  NOT NULL,
    notification_type   VARCHAR(255),
    notification_status VARCHAR(255),
    to_email            VARCHAR(255),
    subject             VARCHAR(255),
    failure_reason      VARCHAR(255),
    CONSTRAINT pk_notifications_aud PRIMARY KEY (rev, id)
);

CREATE TABLE organizations
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_organizations PRIMARY KEY (id)
);

CREATE TABLE organizations_aud
(
    rev     INTEGER NOT NULL,
    revtype SMALLINT,
    id      BIGINT  NOT NULL,
    name    VARCHAR(255),
    CONSTRAINT pk_organizations_aud PRIMARY KEY (rev, id)
);

CREATE TABLE participants
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name          VARCHAR(255)                            NOT NULL,
    last_name           VARCHAR(255)                            NOT NULL,
    email               VARCHAR(255)                            NOT NULL,
    phone_number        VARCHAR(255),
    address             VARCHAR(255),
    registration_source VARCHAR(255),
    CONSTRAINT pk_participants PRIMARY KEY (id)
);

CREATE TABLE participants_aud
(
    rev                 INTEGER NOT NULL,
    revtype             SMALLINT,
    id                  BIGINT  NOT NULL,
    first_name          VARCHAR(255),
    last_name           VARCHAR(255),
    email               VARCHAR(255),
    phone_number        VARCHAR(255),
    address             VARCHAR(255),
    registration_source VARCHAR(255),
    CONSTRAINT pk_participants_aud PRIMARY KEY (rev, id)
);

CREATE TABLE permissions
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    resource VARCHAR(255)                            NOT NULL,
    action   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE permissions_aud
(
    rev      INTEGER NOT NULL,
    revtype  SMALLINT,
    id       BIGINT  NOT NULL,
    name     VARCHAR(255),
    resource VARCHAR(255),
    action   VARCHAR(255),
    CONSTRAINT pk_permissions_aud PRIMARY KEY (rev, id)
);

CREATE TABLE "reset-tokens"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(255),
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT,
    CONSTRAINT "pk_reset-tokens" PRIMARY KEY (id)
);

CREATE TABLE role_permissions
(
    permission_id BIGINT NOT NULL,
    role_id       BIGINT NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (permission_id, role_id)
);

CREATE TABLE role_permissions_aud
(
    permission_id BIGINT  NOT NULL,
    rev           INTEGER NOT NULL,
    revtype       SMALLINT,
    role_id       BIGINT  NOT NULL,
    CONSTRAINT pk_role_permissions_aud PRIMARY KEY (permission_id, rev, role_id)
);

CREATE TABLE roles
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE roles_aud
(
    rev       INTEGER NOT NULL,
    revtype   SMALLINT,
    id        BIGINT  NOT NULL,
    role_name VARCHAR(255),
    CONSTRAINT pk_roles_aud PRIMARY KEY (rev, id)
);

CREATE TABLE session
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    location    VARCHAR(255)                            NOT NULL,
    start_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    mode        VARCHAR(255)                            NOT NULL,
    trainer_id  BIGINT,
    CONSTRAINT pk_session PRIMARY KEY (id)
);

CREATE TABLE session_aud
(
    rev         INTEGER NOT NULL,
    revtype     SMALLINT,
    id          BIGINT  NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    location    VARCHAR(255),
    start_date  TIMESTAMP WITHOUT TIME ZONE,
    end_date    TIMESTAMP WITHOUT TIME ZONE,
    status      VARCHAR(255),
    mode        VARCHAR(255),
    trainer_id  BIGINT,
    CONSTRAINT pk_session_aud PRIMARY KEY (rev, id)
);

CREATE TABLE session_participants
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    training_session_id BIGINT,
    participant_id      BIGINT,
    CONSTRAINT pk_session_participants PRIMARY KEY (id)
);

CREATE TABLE session_participants_aud
(
    rev                 INTEGER NOT NULL,
    revtype             SMALLINT,
    id                  BIGINT  NOT NULL,
    training_session_id BIGINT,
    participant_id      BIGINT,
    CONSTRAINT pk_session_participants_aud PRIMARY KEY (rev, id)
);

CREATE TABLE subsidiaries
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    address         VARCHAR(255)                            NOT NULL,
    organization_id BIGINT,
    CONSTRAINT pk_subsidiaries PRIMARY KEY (id)
);

CREATE TABLE subsidiaries_aud
(
    rev             INTEGER NOT NULL,
    revtype         SMALLINT,
    id              BIGINT  NOT NULL,
    name            VARCHAR(255),
    address         VARCHAR(255),
    organization_id BIGINT,
    CONSTRAINT pk_subsidiaries_aud PRIMARY KEY (rev, id)
);

CREATE TABLE trainer_organizations
(
    organization_id BIGINT NOT NULL,
    trainer_id      BIGINT NOT NULL,
    CONSTRAINT pk_trainer_organizations PRIMARY KEY (organization_id, trainer_id)
);

CREATE TABLE trainer_organizations_aud
(
    organization_id BIGINT  NOT NULL,
    rev             INTEGER NOT NULL,
    revtype         SMALLINT,
    trainer_id      BIGINT  NOT NULL,
    CONSTRAINT pk_trainer_organizations_aud PRIMARY KEY (organization_id, rev, trainer_id)
);

CREATE TABLE trainers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    speciality VARCHAR(255),
    user_id    BIGINT,
    CONSTRAINT pk_trainers PRIMARY KEY (id)
);

CREATE TABLE trainers_aud
(
    rev        INTEGER NOT NULL,
    revtype    SMALLINT,
    id         BIGINT  NOT NULL,
    speciality VARCHAR(255),
    user_id    BIGINT,
    CONSTRAINT pk_trainers_aud PRIMARY KEY (rev, id)
);

CREATE TABLE users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username       VARCHAR(255)                            NOT NULL,
    password       VARCHAR(255)                            NOT NULL,
    first_name     VARCHAR(255)                            NOT NULL,
    last_name      VARCHAR(255)                            NOT NULL,
    email          VARCHAR(255)                            NOT NULL,
    account_status VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_aud
(
    rev            INTEGER NOT NULL,
    revtype        SMALLINT,
    id             BIGINT  NOT NULL,
    username       VARCHAR(255),
    password       VARCHAR(255),
    first_name     VARCHAR(255),
    last_name      VARCHAR(255),
    email          VARCHAR(255),
    account_status VARCHAR(255),
    CONSTRAINT pk_users_aud PRIMARY KEY (rev, id)
);

CREATE TABLE users_roles
(
    user_id  BIGINT NOT NULL,
    roles_id BIGINT NOT NULL
);

CREATE TABLE users_roles_aud
(
    user_id  BIGINT  NOT NULL,
    rev      INTEGER NOT NULL,
    revtype  SMALLINT,
    roles_id BIGINT  NOT NULL,
    CONSTRAINT pk_users_roles_aud PRIMARY KEY (user_id, rev, roles_id)
);

CREATE TABLE verification_token
(
    id          BIGINT NOT NULL,
    token       VARCHAR(255),
    user_id     BIGINT NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_verificationtoken PRIMARY KEY (id)
);

ALTER TABLE organizations
    ADD CONSTRAINT uc_organizations_name UNIQUE (name);

ALTER TABLE permissions
    ADD CONSTRAINT uc_permissions_name UNIQUE (name);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_rolename UNIQUE (role_name);

ALTER TABLE subsidiaries
    ADD CONSTRAINT uc_subsidiaries_name UNIQUE (name);

ALTER TABLE trainers
    ADD CONSTRAINT uc_trainers_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE verification_token
    ADD CONSTRAINT uc_verificationtoken_user UNIQUE (user_id);

ALTER TABLE attendance_aud
    ADD CONSTRAINT FK_ATTENDANCE_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_rev_info (id);

ALTER TABLE attendance
    ADD CONSTRAINT FK_ATTENDANCE_ON_SESSION_PARTICIPANT FOREIGN KEY (session_participant_id) REFERENCES session_participants (id);

ALTER TABLE dashboard_aud
    ADD CONSTRAINT FK_DASHBOARD_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_rev_info (id);

ALTER TABLE export_history_aud
    ADD CONSTRAINT FK_EXPORT_HISTORY_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_rev_info (id);

ALTER TABLE notifications_aud
    ADD CONSTRAINT FK_NOTIFICATIONS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_rev_info (id);

ALTER TABLE organizations_aud
    ADD CONSTRAINT FK_ORGANIZATIONS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_rev_info (id);

ALTER TABLE participants_aud
    ADD CONSTRAINT FK_PARTICIPANTS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_rev_info (id);

ALTER TABLE permissions_aud
    ADD CONSTRAINT FK_PERMISSIONS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_rev_info (id);

ALTER TABLE "reset-tokens"
    ADD CONSTRAINT "FK_RESET-TOKENS_ON_USER" FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE roles_aud
    ADD CONSTRAINT FK_ROLES_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_rev_info (id);

ALTER TABLE session_aud
    ADD CONSTRAINT FK_SESSION_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_rev_info (id);

ALTER TABLE session
    ADD CONSTRAINT FK_SESSION_ON_TRAINER FOREIGN KEY (trainer_id) REFERENCES trainers (id);

ALTER TABLE session_participants_aud
    ADD CONSTRAINT FK_SESSION_PARTICIPANTS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_rev_info (id);

ALTER TABLE session_participants
    ADD CONSTRAINT FK_SESSION_PARTICIPANTS_ON_PARTICIPANT FOREIGN KEY (participant_id) REFERENCES participants (id);

ALTER TABLE session_participants
    ADD CONSTRAINT FK_SESSION_PARTICIPANTS_ON_TRAINING_SESSION FOREIGN KEY (training_session_id) REFERENCES session (id);

ALTER TABLE subsidiaries_aud
    ADD CONSTRAINT FK_SUBSIDIARIES_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_rev_info (id);

ALTER TABLE subsidiaries
    ADD CONSTRAINT FK_SUBSIDIARIES_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id);

ALTER TABLE trainers_aud
    ADD CONSTRAINT FK_TRAINERS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_rev_info (id);

ALTER TABLE trainers
    ADD CONSTRAINT FK_TRAINERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users_aud
    ADD CONSTRAINT FK_USERS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_rev_info (id);

ALTER TABLE verification_token
    ADD CONSTRAINT FK_VERIFICATIONTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE role_permissions_aud
    ADD CONSTRAINT fk_role_permissions_aud_on_rev FOREIGN KEY (rev) REFERENCES custom_rev_info (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_permission FOREIGN KEY (permission_id) REFERENCES permissions (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE trainer_organizations_aud
    ADD CONSTRAINT fk_trainer_organizations_aud_on_rev FOREIGN KEY (rev) REFERENCES custom_rev_info (id);

ALTER TABLE trainer_organizations
    ADD CONSTRAINT fk_traorg_on_organization FOREIGN KEY (organization_id) REFERENCES organizations (id);

ALTER TABLE trainer_organizations
    ADD CONSTRAINT fk_traorg_on_trainer FOREIGN KEY (trainer_id) REFERENCES trainers (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (roles_id) REFERENCES roles (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users_roles_aud
    ADD CONSTRAINT fk_users_roles_aud_on_rev FOREIGN KEY (rev) REFERENCES custom_rev_info (id);