spring.application.name=BeModule


spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:NAME
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=