spring:
  application:
    name: BeModule
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: myuser
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: a81169001@smtp-brevo.com
    password: xsmtpsib-9e255abbe5e1ba1044c13834971fceeec263985083207230173466bd17bfca52-Z4MlVAFpOuFdqh87
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081


jwt:
  secret: mySecretKey1234567890123456789012345678901234567890
  expiration: 86400000 # 24 h
  refresh-expiration: 604800000 # 7 days in milliseconds


management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]