package cires.bemodule.enums;;

public enum NotificationType {
    ACCOUNT_CREATION,
    PASSWORD_RESET,
    TRAINER_ASSIGNMENT,
    SESSION_REMINDER,
    SESSION_CANCELLATION,
    ATTENDANCE_VALIDATED,
    SESSION_POSTPONED,
    EXPORT_READY
}