package cires.bemodule.enums;

/**
 * Types of reports that can be generated by the
 * {@link cires.bemodule.services.ReportService}.
 * <p>
 * Each value corresponds to a specific report template and data set.
 * </p>
 */
public enum ReportType {

    /** Overall attendance rate per session and aggregated metrics. */
    ATTENDANCE_RATE,

    /** Detailed list of absences (both justified and unjustified). */
    ABSENCE_SUMMARY,

    /** Attendance breakdown grouped by subsidiary (filiale). */
    SUBSIDIARY_BREAKDOWN
}